(function (root, factory) {
  const api = factory();
  root.POSBizHub = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const ALL = "*";

  function shopKind(biz) {
    return globalThis.POSFootwear?.shopKind?.(biz) || "general";
  }

  function matchKinds(kinds, kind) {
    if (!kinds || kinds === ALL || kinds.includes(ALL)) return true;
    return kinds.includes(kind);
  }

  const MODULES = [
    { id: "dashboard", group: "home", title: "Dashboard", view: "dashboard", perm: "dashboard" },
    { id: "counter", group: "sales", title: "Counter POS", view: "counter", perm: "counter" },
    { id: "invoices", group: "sales", title: "Sales Invoice", view: "orders", perm: "orders" },
    { id: "new-invoice", group: "sales", title: "New Invoice", view: "counter", perm: "counter" },
    { id: "quotation", group: "sales", title: "Quotation", view: "hub-sales", perm: "orders", desk: "quotation" },
    { id: "sales-order", group: "sales", title: "Sales Order", view: "hub-sales", perm: "orders", desk: "sales-order" },
    { id: "challan", group: "sales", title: "Delivery Challan", view: "hub-sales", perm: "orders", desk: "challan" },
    { id: "recurring", group: "sales", title: "Recurring Invoice", view: "hub-sales", perm: "orders", desk: "recurring" },
    { id: "credit-note", group: "sales", title: "Credit Note", view: "returns", perm: "orders", kinds: ["pharmacy", "apparel", "footwear"] },
    { id: "sales-return", group: "sales", title: "Sales Return", view: "returns", perm: "orders", kinds: ["pharmacy", "apparel", "footwear"] },
    { id: "cancelled", group: "sales", title: "Cancelled Invoice", view: "orders", perm: "orders", query: "cancelled" },
    { id: "receipt", group: "sales", title: "Payment Receipt", view: "payments", perm: "accounts" },
    { id: "customer-due", group: "sales", title: "Customer Due", view: "customers", perm: "customers" },
    { id: "customer-ledger", group: "sales", title: "Customer Ledger", view: "accounts", perm: "accounts", acc: "customer-ledger" },
    { id: "purchase-request", group: "purchases", title: "Purchase Request", view: "hub-purchases", perm: "purchases", desk: "pr", blurb: "Ask for stock before you order" },
    { id: "purchase-order", group: "purchases", title: "Purchase Order", view: "hub-purchases", perm: "purchases", desk: "po", blurb: "Confirm what to buy from a supplier" },
    { id: "grn", group: "purchases", title: "Goods Receipt", view: "hub-purchases", perm: "purchases", desk: "grn", blurb: "Record goods received at the shop" },
    { id: "purchase-invoice", group: "purchases", title: "Purchase Invoice", view: "purchases", perm: "purchases", open: "purchase-new", blurb: "Supplier bill — this posts stock" },
    { id: "debit-note", group: "purchases", title: "Debit Note", view: "hub-purchases", perm: "purchases", desk: "debit", blurb: "Claim against a supplier bill" },
    { id: "purchase-return", group: "purchases", title: "Purchase Return", view: "hub-purchases", perm: "purchases", desk: "preturn", blurb: "Send goods back to the supplier" },
    { id: "supplier-pay", group: "purchases", title: "Supplier Payment", view: "payments", perm: "accounts", highlight: "supplier-pay", blurb: "Pay a supplier from payables" },
    { id: "supplier-due", group: "purchases", title: "Supplier Due", view: "accounts", perm: "accounts", acc: "payables", blurb: "What we still owe suppliers" },
    { id: "supplier-ledger", group: "purchases", title: "Supplier Ledger", view: "accounts", perm: "accounts", acc: "supplier-ledger", blurb: "Supplier account history" },
    { id: "customers", group: "customers", title: "Customer Master", view: "customers", perm: "customers" },
    { id: "customer-groups", group: "customers", title: "Customer Groups", view: "customers", perm: "customers" },
    { id: "opening-balance", group: "customers", title: "Opening Balance", view: "customers", perm: "customers" },
    { id: "credit-limit", group: "customers", title: "Credit Limit", view: "customers", perm: "customers" },
    { id: "customer-statement", group: "customers", title: "Customer Statement", view: "accounts", perm: "accounts", acc: "customer-ledger" },
    { id: "sales-history", group: "customers", title: "Sales History", report: "sales-by-customer", perm: "reports" },
    { id: "payment-history", group: "customers", title: "Payment History", report: "payment-received", perm: "reports" },
    { id: "outstanding-cust", group: "customers", title: "Outstanding", view: "customers", perm: "customers" },
    { id: "due-aging", group: "customers", title: "Due Aging", report: "due-aging", perm: "reports" },
    { id: "cust-profit", group: "customers", title: "Customer-wise Profit", report: "profit-by-invoice", perm: "reports" },
    { id: "cust-sales", group: "customers", title: "Customer-wise Sales", report: "sales-by-customer", perm: "reports" },
    { id: "suppliers", group: "suppliers", title: "Supplier Master", view: "suppliers", perm: "suppliers" },
    { id: "supplier-groups", group: "suppliers", title: "Supplier Groups", view: "suppliers", perm: "suppliers" },
    { id: "supplier-opening", group: "suppliers", title: "Opening Balance", view: "suppliers", perm: "suppliers" },
    { id: "purchase-history", group: "suppliers", title: "Purchase History", report: "supplier-purchase", perm: "reports" },
    { id: "supplier-pay-hist", group: "suppliers", title: "Payment History", report: "payment-made", perm: "reports" },
    { id: "supplier-out", group: "suppliers", title: "Outstanding", view: "accounts", perm: "accounts", acc: "payables" },
    { id: "supplier-aging", group: "suppliers", title: "Due Aging", report: "supplier-aging", perm: "reports" },
    { id: "supplier-wise", group: "suppliers", title: "Supplier-wise Purchase", report: "supplier-purchase", perm: "reports" },
    { id: "items", group: "products", title: "Product Master", view: "items", perm: "items" },
    { id: "services", group: "products", title: "Service Master", view: "items", perm: "items", kinds: ["services", "salon", "electronics"] },
    { id: "categories", group: "products", title: "Categories", view: "items", perm: "items" },
    { id: "brands", group: "products", title: "Brands", view: "items", perm: "items", kinds: ["apparel", "footwear", "electronics", "pharmacy"] },
    { id: "units", group: "products", title: "Units", view: "units", perm: "items" },
    { id: "hsn", group: "products", title: "HSN/SAC", view: "items", perm: "items" },
    { id: "gst-tax", group: "products", title: "GST/Tax", report: "tax-summary", perm: "reports" },
    { id: "barcode", group: "products", title: "Barcode", view: "barcodes", perm: "items" },
    { id: "price-list", group: "products", title: "Price List", view: "items", perm: "items" },
    { id: "purchase-price", group: "products", title: "Purchase Price", view: "items", perm: "items" },
    { id: "selling-price", group: "products", title: "Selling Price", view: "items", perm: "items" },
    { id: "stock", group: "products", title: "Stock", view: "stock", perm: "stock" },
    { id: "min-stock", group: "products", title: "Minimum Stock", report: "low-stock", perm: "stock" },
    { id: "opening-stock", group: "products", title: "Opening Stock", view: "stock", perm: "stock" },
    { id: "stock-adj", group: "products", title: "Stock Adjustment", view: "stock", perm: "stock" },
    { id: "stock-xfer", group: "products", title: "Stock Transfer", view: "stock", perm: "stock" },
    { id: "payments", group: "payments", title: "Payments", view: "payments", perm: "accounts" },
    { id: "coa", group: "accounting", title: "Chart of Accounts", view: "accounts", perm: "accounts", acc: "coa" },
    { id: "cash-account", group: "accounting", title: "Cash Account", view: "accounts", perm: "accounts", acc: "cash-book" },
    { id: "bank-account", group: "accounting", title: "Bank Account", view: "accounts", perm: "accounts", acc: "cash-book" },
    { id: "ar", group: "accounting", title: "Customer Receivable", view: "accounts", perm: "accounts", acc: "receivables" },
    { id: "ap", group: "accounting", title: "Supplier Payable", view: "accounts", perm: "accounts", acc: "payables" },
    { id: "sales-account", group: "accounting", title: "Sales Account", view: "accounts", perm: "accounts", acc: "profit-loss" },
    { id: "purchase-account", group: "accounting", title: "Purchase Account", view: "accounts", perm: "accounts", acc: "profit-loss" },
    { id: "expense-account", group: "accounting", title: "Expense Account", view: "expenses", perm: "accounts" },
    { id: "income-account", group: "accounting", title: "Income Account", view: "accounts", perm: "accounts", acc: "profit-loss" },
    { id: "journal", group: "accounting", title: "Journal Entry", view: "accounts", perm: "accounts", acc: "journal" },
    { id: "contra", group: "accounting", title: "Contra Entry", view: "accounts", perm: "accounts", acc: "journal" },
    { id: "gl", group: "accounting", title: "General Ledger", view: "accounts", perm: "accounts", acc: "journal" },
    { id: "tb", group: "accounting", title: "Trial Balance", view: "accounts", perm: "accounts", acc: "trial-balance" },
    { id: "pl", group: "accounting", title: "Profit & Loss", view: "accounts", perm: "accounts", acc: "profit-loss" },
    { id: "bs", group: "accounting", title: "Balance Sheet", view: "accounts", perm: "accounts", acc: "balance-sheet" },
    { id: "cash-flow", group: "accounting", title: "Cash Flow", view: "accounts", perm: "accounts", acc: "cash-book" },
    { id: "expenses", group: "expenses", title: "Expense Entry", view: "expenses", perm: "accounts" },
    { id: "expense-cats", group: "expenses", title: "Expense Categories", view: "expenses", perm: "accounts" },
    { id: "reports", group: "reports", title: "Reports Center", view: "reports", perm: "reports" },
    { id: "audit", group: "admin", title: "Activity Log", view: "audit", perm: "settings" },
    { id: "rx-batch", group: "industry", title: "Batch", view: "stock", perm: "stock", kinds: ["pharmacy"] },
    { id: "rx-expiry", group: "industry", title: "Expiry", view: "expiry", perm: "stock", kinds: ["pharmacy", "grocery"] },
    { id: "rx-mrp", group: "industry", title: "MRP", view: "items", perm: "items", kinds: ["pharmacy"] },
    { id: "rx-strip", group: "industry", title: "Strip/Box/Unit", view: "items", perm: "items", kinds: ["pharmacy"] },
    { id: "rx-licence", group: "industry", title: "Drug Licence", view: "settings", perm: "settings", kinds: ["pharmacy"] },
    { id: "rx", group: "industry", title: "Prescription", view: "prescriptions", perm: "orders", kinds: ["pharmacy"] },
    { id: "rx-doctor", group: "industry", title: "Doctor", view: "customers", perm: "customers", kinds: ["pharmacy"] },
    { id: "rx-return", group: "industry", title: "Medicine Return", view: "returns", perm: "orders", kinds: ["pharmacy"] },
    { id: "garment-size", group: "industry", title: "Size", view: "items", perm: "items", kinds: ["apparel", "footwear"] },
    { id: "garment-colour", group: "industry", title: "Colour", view: "items", perm: "items", kinds: ["apparel", "footwear"] },
    { id: "garment-brand", group: "industry", title: "Brand", view: "items", perm: "items", kinds: ["apparel", "footwear"] },
    { id: "garment-style", group: "industry", title: "Style", view: "items", perm: "items", kinds: ["apparel"] },
    { id: "garment-sku", group: "industry", title: "SKU / Variant", view: "items", perm: "items", kinds: ["apparel", "footwear"] },
    { id: "garment-size-stock", group: "industry", title: "Size-wise stock", view: "stock", perm: "stock", kinds: ["apparel", "footwear"] },
    { id: "garment-colour-stock", group: "industry", title: "Colour-wise stock", view: "stock", perm: "stock", kinds: ["apparel", "footwear"] },
    { id: "resto-table", group: "industry", title: "Table", view: "counter", perm: "counter", kinds: ["restaurant"] },
    { id: "resto-kot", group: "industry", title: "KOT", view: "kot", perm: "kot", kinds: ["restaurant"] },
    { id: "resto-dine", group: "industry", title: "Dine-in", view: "counter", perm: "counter", kinds: ["restaurant"] },
    { id: "resto-takeaway", group: "industry", title: "Takeaway", view: "counter", perm: "counter", kinds: ["restaurant"] },
    { id: "resto-delivery", group: "industry", title: "Delivery", view: "qr-orders", perm: "orders", kinds: ["restaurant"] },
    { id: "resto-qr", group: "industry", title: "QR Ordering", view: "qr-orders", perm: "orders", kinds: ["restaurant"] },
    { id: "resto-kds", group: "industry", title: "Kitchen Display", view: "kot", perm: "kot", kinds: ["restaurant"] },
    { id: "groc-weight", group: "industry", title: "Weight / Unit", view: "units", perm: "items", kinds: ["grocery", "spice"] },
    { id: "groc-barcode", group: "industry", title: "Barcode", view: "barcodes", perm: "items", kinds: ["grocery", "spice"] },
    { id: "groc-batch", group: "industry", title: "Batch", view: "stock", perm: "stock", kinds: ["grocery"] },
    { id: "groc-expiry", group: "industry", title: "Expiry", view: "expiry", perm: "stock", kinds: ["grocery"] },
    { id: "groc-pack", group: "industry", title: "Loose/Pack", view: "packs", perm: "items", kinds: ["spice", "grocery"] },
    { id: "el-serial", group: "industry", title: "Serial Number", view: "barcodes", perm: "items", kinds: ["electronics"] },
    { id: "el-imei", group: "industry", title: "IMEI", view: "barcodes", perm: "items", kinds: ["electronics"] },
    { id: "el-warranty", group: "industry", title: "Warranty", view: "items", perm: "items", kinds: ["electronics"] },
    { id: "el-service", group: "industry", title: "Service / Repair", view: "items", perm: "items", kinds: ["electronics"] },
    { id: "salon-svc", group: "industry", title: "Services", view: "items", perm: "items", kinds: ["services"] },
    { id: "salon-staff", group: "industry", title: "Staff / Commission", view: "staff", perm: "staff", kinds: ["services"] },
    { id: "svc-job", group: "industry", title: "Job Card / Service Order", view: "orders", perm: "orders", kinds: ["services"] },
  ];

  const GROUPS = [
    { id: "home", title: "Home" },
    { id: "sales", title: "Sales" },
    { id: "purchases", title: "Purchases" },
    { id: "customers", title: "Customers" },
    { id: "suppliers", title: "Suppliers" },
    { id: "products", title: "Products / Services" },
    { id: "payments", title: "Payments" },
    { id: "accounting", title: "Accounting" },
    { id: "expenses", title: "Expenses" },
    { id: "reports", title: "Reports" },
    { id: "industry", title: "Business type" },
    { id: "admin", title: "Admin" },
  ];

  const REPORTS = [
    { id: "daily-sales", center: "sales", title: "Daily Sales", tab: "sales", sheet: "Sales bills" },
    { id: "monthly-sales", center: "sales", title: "Monthly Sales", tab: "sales", sheet: "Sales bills" },
    { id: "yearly-sales", center: "sales", title: "Yearly Sales", tab: "sales", sheet: "Sales bills" },
    { id: "sales-by-customer", center: "sales", title: "Sales by Customer", tab: "sales", sheet: "Customer sales" },
    { id: "sales-by-product", center: "sales", title: "Sales by Product", tab: "sales", sheet: "Item sales" },
    { id: "sales-by-category", center: "sales", title: "Sales by Category", tab: "sales", sheet: "Item sales" },
    { id: "sales-by-brand", center: "sales", title: "Sales by Brand", tab: "sales", sheet: "Item sales", kinds: ["apparel", "footwear", "electronics", "pharmacy"] },
    { id: "sales-by-user", center: "sales", title: "Sales by User", tab: "sales", sheet: "Sales bills" },
    { id: "sales-by-counter", center: "sales", title: "Sales by Counter", tab: "sales", sheet: "Sales bills" },
    { id: "sales-by-pay", center: "sales", title: "Sales by Payment Mode", tab: "payment", sheet: "Payment" },
    { id: "sales-return", center: "sales", title: "Sales Return", tab: "sales", sheet: "Sales bills", kinds: ["pharmacy", "apparel", "footwear"] },
    { id: "cancelled-sales", center: "sales", title: "Cancelled Sales", tab: "sales", sheet: "Cancelled sales" },
    { id: "discount-report", center: "sales", title: "Discount Report", tab: "sales", sheet: "Sales bills" },
    { id: "tax-report", center: "tax", title: "Tax Report", tab: "gst", sheet: "GST summary" },
    { id: "profit-by-invoice", center: "profitability", title: "Profit by Invoice", tab: "sales", sheet: "Sales bills" },
    { id: "gross-profit", center: "profitability", title: "Gross Profit", tab: "summary", sheet: "" },
    { id: "sales-outstanding", center: "sales", title: "Sales Outstanding", tab: "books", sheet: "Customers" },
    { id: "daily-purchase", center: "purchase", title: "Daily Purchase", tab: "books", sheet: "Purchases" },
    { id: "monthly-purchase", center: "purchase", title: "Monthly Purchase", tab: "books", sheet: "Purchases" },
    { id: "supplier-purchase", center: "purchase", title: "Supplier-wise Purchase", tab: "books", sheet: "Purchases" },
    { id: "product-purchase", center: "purchase", title: "Product-wise Purchase", tab: "books", sheet: "Purchases" },
    { id: "category-purchase", center: "purchase", title: "Category-wise Purchase", tab: "books", sheet: "Purchases" },
    { id: "purchase-return", center: "purchase", title: "Purchase Return", tab: "books", sheet: "Purchases" },
    { id: "purchase-tax", center: "purchase", title: "Purchase Tax", tab: "gst", sheet: "GST input by rate" },
    { id: "purchase-outstanding", center: "purchase", title: "Purchase Outstanding", tab: "books", sheet: "Purchases" },
    { id: "purchase-price-history", center: "purchase", title: "Purchase Price History", tab: "stock", sheet: "Stock" },
    { id: "supplier-performance", center: "purchase", title: "Supplier Performance", tab: "books", sheet: "Purchases" },
    { id: "current-stock", center: "inventory", title: "Current Stock", tab: "stock", sheet: "Stock" },
    { id: "stock-valuation", center: "inventory", title: "Stock Valuation", tab: "stock", sheet: "Stock" },
    { id: "stock-movement", center: "inventory", title: "Stock Movement", view: "ledger" },
    { id: "stock-ledger", center: "inventory", title: "Stock Ledger", view: "ledger" },
    { id: "stock-in", center: "inventory", title: "Stock In", view: "ledger" },
    { id: "stock-out", center: "inventory", title: "Stock Out", view: "ledger" },
    { id: "stock-adjustment", center: "inventory", title: "Stock Adjustment", view: "stock" },
    { id: "stock-transfer", center: "inventory", title: "Stock Transfer", view: "stock" },
    { id: "low-stock", center: "inventory", title: "Low Stock", tab: "stock", sheet: "Low stock" },
    { id: "out-of-stock", center: "inventory", title: "Out of Stock", tab: "stock", sheet: "Low stock" },
    { id: "fast-moving", center: "inventory", title: "Fast Moving", tab: "sales", sheet: "Item sales" },
    { id: "slow-moving", center: "inventory", title: "Slow Moving", tab: "sales", sheet: "Item sales" },
    { id: "dead-stock", center: "inventory", title: "Dead Stock", tab: "stock", sheet: "Stock" },
    { id: "negative-stock", center: "inventory", title: "Negative Stock", tab: "stock", sheet: "Stock" },
    { id: "expiry-report", center: "inventory", title: "Expiry Report", view: "expiry", kinds: ["pharmacy", "grocery"] },
    { id: "batch-report", center: "inventory", title: "Batch Report", view: "stock", kinds: ["pharmacy", "grocery"] },
    { id: "payment-received", center: "payments", title: "Payment Received", tab: "payment", sheet: "Payment" },
    { id: "payment-made", center: "payments", title: "Payment Made", tab: "books", sheet: "Purchases" },
    { id: "payment-receipt", center: "payments", title: "Payment Receipt", view: "payments" },
    { id: "payment-voucher", center: "payments", title: "Payment Voucher", view: "payments" },
    { id: "payment-mode", center: "payments", title: "Payment Mode Report", tab: "payment", sheet: "Payment" },
    { id: "cash-book", center: "payments", title: "Cash Book", view: "accounts", acc: "cash-book" },
    { id: "bank-book", center: "payments", title: "Bank Book", view: "accounts", acc: "cash-book" },
    { id: "upi-collection", center: "payments", title: "UPI Collection", tab: "payment", sheet: "Payment daywise" },
    { id: "cheque-pending", center: "payments", title: "Cheque Pending", tab: "payment", sheet: "Payment" },
    { id: "payment-recon", center: "payments", title: "Payment Reconciliation", tab: "payment", sheet: "Payment daywise" },
    { id: "deleted-payments", center: "payments", title: "Deleted/Cancelled Payments", view: "audit" },
    { id: "expense-report", center: "expenses", title: "Expense Report", tab: "books", sheet: "Expenses" },
    { id: "expense-by-cat", center: "expenses", title: "Expense by Category", tab: "books", sheet: "Expenses" },
    { id: "expense-by-user", center: "expenses", title: "Expense by User", tab: "books", sheet: "Expenses" },
    { id: "pl", center: "accounting", title: "Profit & Loss", view: "accounts", acc: "profit-loss" },
    { id: "cogs", center: "accounting", title: "Cost of Goods", view: "accounts", acc: "profit-loss" },
    { id: "net-profit", center: "accounting", title: "Net Profit", view: "accounts", acc: "profit-loss" },
    { id: "balance-sheet", center: "accounting", title: "Balance Sheet", view: "accounts", acc: "balance-sheet" },
    { id: "trial-balance", center: "accounting", title: "Trial Balance", view: "accounts", acc: "trial-balance" },
    { id: "general-ledger", center: "accounting", title: "General Ledger", view: "accounts", acc: "journal" },
    { id: "cash-flow", center: "accounting", title: "Cash Flow", view: "accounts", acc: "cash-book" },
    { id: "day-book", center: "accounting", title: "Day Book", view: "accounts", acc: "ledger" },
    { id: "account-statement", center: "accounting", title: "Account Statement", view: "accounts", acc: "customer-ledger" },
    { id: "gst-sales", center: "tax", title: "GST Sales", tab: "gst", sheet: "GST B2B sales" },
    { id: "gst-purchase", center: "tax", title: "GST Purchase", tab: "gst", sheet: "GST input by rate" },
    { id: "output-gst", center: "tax", title: "Output GST", tab: "gst", sheet: "GST output by rate" },
    { id: "input-gst", center: "tax", title: "Input GST", tab: "gst", sheet: "GST input by rate" },
    { id: "cgst", center: "tax", title: "CGST", tab: "gst", sheet: "GST summary" },
    { id: "sgst", center: "tax", title: "SGST", tab: "gst", sheet: "GST summary" },
    { id: "igst", center: "tax", title: "IGST", tab: "gst", sheet: "GST summary" },
    { id: "taxable", center: "tax", title: "Taxable Amount", tab: "gst", sheet: "GST daywise" },
    { id: "tax-summary", center: "tax", title: "Tax Summary", tab: "gst", sheet: "GST summary" },
    { id: "hsn-summary", center: "tax", title: "HSN/SAC Summary", tab: "gst", sheet: "GST HSN itemwise" },
    { id: "gst-register", center: "tax", title: "GST Invoice Register", tab: "gst", sheet: "GST B2C sales" },
    { id: "gst-credit", center: "tax", title: "Credit Note", tab: "gst", sheet: "GST summary" },
    { id: "gst-debit", center: "tax", title: "Debit Note", tab: "gst", sheet: "GST summary" },
    { id: "gst-export", center: "tax", title: "GST Return Data Export", tab: "gst", sheet: "GST summary" },
    { id: "due-aging", center: "customers", title: "Due Aging", tab: "books", sheet: "Customers" },
    { id: "supplier-aging", center: "suppliers", title: "Supplier Due Aging", view: "accounts", acc: "payables" },
    { id: "audit-log", center: "audit", title: "Audit Log", view: "audit" },
    { id: "analytics", center: "analytics", title: "Business Analytics", view: "growth" },
    { id: "employees", center: "employees", title: "Employees", view: "staff" },
  ];

  const CENTERS = [
    { id: "sales", title: "Sales" },
    { id: "purchase", title: "Purchase" },
    { id: "inventory", title: "Inventory" },
    { id: "customers", title: "Customers" },
    { id: "suppliers", title: "Suppliers" },
    { id: "payments", title: "Payments" },
    { id: "expenses", title: "Expenses" },
    { id: "accounting", title: "Accounting" },
    { id: "tax", title: "Tax/GST" },
    { id: "profitability", title: "Profitability" },
    { id: "employees", title: "Employees" },
    { id: "analytics", title: "Business Analytics" },
    { id: "audit", title: "Audit Log" },
  ];

  const PURCHASE_DOC_KINDS = {
    pr: {
      title: "Purchase Request",
      prefix: "PR",
      save: "Save request",
      hint: "Internal ask for stock. Convert to a purchase order when approved. Stock is not posted here.",
      statuses: ["Draft", "Sent", "Approved"],
    },
    po: {
      title: "Purchase Order",
      prefix: "PO",
      save: "Save order",
      hint: "Confirm what to buy. Receive with a goods receipt, then post stock on Purchase Invoice.",
      statuses: ["Draft", "Sent", "Confirmed"],
    },
    grn: {
      title: "Goods Receipt",
      prefix: "GRN",
      save: "Save receipt",
      hint: "Record what arrived. On-hand stock still posts through Purchase Invoice.",
      statuses: ["Draft", "Received"],
    },
    debit: {
      title: "Debit Note",
      prefix: "DN",
      save: "Save debit note",
      hint: "Claim shortage, rate difference, or return value against a supplier bill.",
      statuses: ["Draft", "Issued"],
    },
    preturn: {
      title: "Purchase Return",
      prefix: "PRT",
      save: "Save return",
      hint: "Send goods back. Reverse stock on Purchases if the original bill already posted.",
      statuses: ["Draft", "Returned"],
    },
  };

  const PAY_MODES = ["cash", "upi", "card", "bank-transfer", "neft", "rtgs", "imps", "cheque", "wallet", "other"];

  const DASH_KPIS = [
    { key: "todaySales", label: "Today's Sales", view: "orders", money: true },
    { key: "todayPurchases", label: "Today's Purchases", view: "purchases", money: true },
    { key: "todayReceipts", label: "Today's Receipts", view: "payments", money: true },
    { key: "todayPayments", label: "Today's Payments", view: "payments", money: true },
    { key: "receivable", label: "Total Receivable", view: "customers", money: true },
    { key: "payable", label: "Total Payable", view: "accounts", money: true },
    { key: "cashBalance", label: "Cash Balance", view: "accounts", money: true },
    { key: "bankBalance", label: "Bank/UPI Balance", view: "accounts", money: true },
    { key: "grossProfit", label: "Gross Profit", view: "reports", money: true },
    { key: "netProfit", label: "Net Profit", view: "reports", money: true },
    { key: "expenses", label: "Expenses", view: "expenses", money: true },
    { key: "stockValue", label: "Stock Value", view: "stock", money: true },
    { key: "lowStock", label: "Low Stock", view: "stock", money: false },
    { key: "outstandingCustomers", label: "Outstanding Customers", view: "customers", money: false },
    { key: "outstandingSuppliers", label: "Outstanding Suppliers", view: "accounts", money: false },
  ];

  function modulesFor(biz) {
    const kind = shopKind(biz);
    return MODULES.filter((m) => matchKinds(m.kinds, kind));
  }

  function reportsFor(biz) {
    const kind = shopKind(biz);
    return REPORTS.filter((r) => matchKinds(r.kinds, kind));
  }

  function reportsByCenter(biz) {
    const kind = shopKind(biz);
    return CENTERS.map((c) => ({
      ...c,
      reports: REPORTS.filter((r) => r.center === c.id && matchKinds(r.kinds, kind)),
    })).filter((c) => c.reports.length);
  }

  return {
    ALL,
    MODULES,
    GROUPS,
    PURCHASE_DOC_KINDS,
    REPORTS,
    CENTERS,
    PAY_MODES,
    DASH_KPIS,
    shopKind,
    matchKinds,
    modulesFor,
    reportsFor,
    reportsByCenter,
  };
});
