import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const read = (rel) => readFileSync(path.join(root, rel), "utf8");

test("public homepage matches ATAV TELECOM reference layout", () => {
  const home = read("home.html");
  const css = read("css/marketing.css");
  const js = read("js/marketing.js");
  const server = read("server/index.js");
  const loginJs = read("js/x-pos-20260830e.js");
  const deploy = read("DEPLOY-FILES.txt");
  const ht = read(".htaccess");

  assert.match(home, /Welcome to ATAV TELECOM/);
  assert.match(home, /Talk to Our Expert/);
  assert.match(home, /Request Demo/);
  assert.match(home, /href="\.\/login\.html"/);
  assert.match(home, /SMART BUSINESS SOLUTION/);
  assert.match(home, /<h1>ATAV POS<\/h1>/);
  assert.match(home, /Billing \| Inventory \| Customers \| Reports/);
  assert.match(home, /Get Free Demo/);
  assert.match(home, /SUITABLE FOR ALL TYPES OF BUSINESSES/);
  assert.match(home, /Pharmacy &amp; Medical/);
  assert.match(home, /Powerful Features/);
  assert.match(home, /Happy Businesses/);
  assert.match(home, /Manage Your Business/);
  assert.match(home, /What Our Customers Say/);
  assert.match(home, /Ready to Transform Your Business\?/);
  assert.match(home, /Connecting Your Business/);
  assert.match(home, /Smart Business\. Smarter Tomorrow\./);
  assert.match(home, /\+91 97650 40588/);
  assert.match(home, /tel:\+919765040588/);
  assert.match(home, /wa\.me\/919765040588/);
  assert.doesNotMatch(home, /7757090344/);
  assert.match(home, /data-hero-slider/);
  assert.match(home, /Smart Billing/);
  assert.doesNotMatch(home, /id="view-orders"/);
  assert.match(home, /marketing\.css\?v=20260920atav2/);
  assert.match(home, /marketing\.js\?v=20260920atav2/);
  assert.match(css, /--orange: #f58220/);
  assert.match(css, /--blue: #073b82/);
  assert.match(js, /data-hero-slider/);
  assert.match(js, /BUSINESS_TYPES/);
  assert.match(js, /mailto:info@atavtelecom\.in/);
  assert.match(server, /sendFile\(path\.join\(publicDir, "home\.html"\)\)/);
  assert.match(loginJs, /location\.href = "\/index\.html"/);
  assert.match(deploy, /home\.html/);
  assert.match(ht, /DirectoryIndex home\.html index\.html/);
});
