import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { execFileSync, spawnSync } from "node:child_process";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

function hasPhpCli() {
  return spawnSync("php", ["-v"], { encoding: "utf8" }).status === 0;
}

function read(name) {
  return readFileSync(path.join(root, name), "utf8");
}

test("PHP fallback routes checkout, holds, and order updates through core", () => {
  const core = read("pos-php-core.php");
  const till = read("pos-php-till.php");
  const crud = read("pos-crud.php");
  const checkout = read("pos-checkout.php");
  const holds = read("pos-holds.php");
  const orders = read("pos-orders.php");

  assert.match(core, /checkout.*POST.*pos_dispatch_checkout/s);
  assert.match(core, /orders\/\[\^\/\]\+.*pos_dispatch_order_route/s);
  assert.match(core, /holds.*pos_dispatch_holds/s);
  assert.match(core, /backup.*pos_dispatch_backup/s);
  assert.match(core, /pos_dispatch_master_backup/);
  assert.match(core, /units.*pos_dispatch_units/s);
  assert.match(core, /function pos_require_backup/);
  assert.match(core, /function pos_require_units/);
  assert.match(core, /function pos_require_advanced/);
  assert.match(core, /pos_dispatch_advanced/);
  assert.match(core, /function pos_round2/);
  assert.match(core, /function pos_ensure_held_bills_schema/);
  assert.match(till, /pos_dispatch_order_route/);
  assert.match(till, /pos_dispatch_holds/);
  assert.match(crud, /checkout.*POST.*pos_dispatch_checkout/s);
  assert.match(crud, /pos_dispatch_holds/);
  assert.match(core, /function pos_customer_label/);
  assert.match(checkout, /pos_customer_label\(\$customer\)/);
  assert.match(orders, /pos_customer_label\(\$customer\)/);
  assert.doesNotMatch(checkout, /\$customer\["business_name"\] \?\? \$customer\["name"\]/);
  assert.doesNotMatch(orders, /\$customer\["business_name"\] \?\? \$customer\["name"\]/);
  assert.match(till, /NULLIF\(TRIM\(o\.customer_name\)/);
  assert.match(read("server/index.js"), /NULLIF\(TRIM\(o\.customer_name\)/);
  assert.match(checkout, /function pos_checkout_sale/);
  assert.match(checkout, /pos_alert_low_stock/);
  assert.match(checkout, /pos_tick_shop_alerts/);
  assert.match(holds, /function pos_dispatch_holds/);
  assert.match(holds, /INSERT INTO held_bills/);
  assert.match(holds, /payload\["table_no"\]/);
  assert.match(checkout, /table_no = \?/);
  assert.match(read("server/index.js"), /table_no = \?/);
  assert.match(read("pos-qr-ordering.php"), /table_no = \?/);
  assert.match(orders, /function pos_dispatch_order_route/);
  assert.match(orders, /function pos_delete_order/);
  assert.match(orders, /\$method === "DELETE"/);
  assert.match(orders, /pos_require_business_admin_delete/);
  assert.match(read("server/crud.js"), /app.delete\("\/api\/orders\/:id"/);
  assert.match(read("server/crud.js"), /Only the business admin can delete invoices/);
  assert.match(read("server/accounts.js"), /export async function reverseCreditSale/);
  assert.match(read("server/accounts.js"), /export async function recomputeCustomerOutstanding/);
  assert.match(read("pos-php-core.php"), /function pos_reverse_credit_sale/);
  assert.match(read("pos-php-core.php"), /function pos_recompute_customer_outstanding/);
  assert.match(read("js/app.js"), /function canDeleteInvoice/);
  assert.match(read("js/app.js"), /data-delete-order/);
  assert.match(core, /This POS action is not available in PHP fallback yet \(\{\$method\} \{\$path\}\)/);
  assert.match(read("pos-accounting.php"), /\$path === "expenses"/);
  assert.match(read("pos-accounting.php"), /accounts\/receipts\/\(\[\^\/\]\+\)/);
  assert.match(read("pos-accounting.php"), /function pos_replace_ledger_journal/);
  assert.match(read("pos-accounting.php"), /function pos_delete_ledger_journal/);
  assert.match(read("pos-accounting.php"), /\$method === "DELETE"/);
  assert.match(read("pos-php-core.php"), /function pos_indian_fy/);
  assert.match(read("pos-php-core.php"), /function pos_public_invoice_send/);
  assert.match(read("server/index.js"), /app\.get\("\/api\/invoices\/:id"/);
  assert.match(read("js/app.js"), /function invoiceShareButtons/);
  assert.match(read("js/app.js"), /Share WhatsApp/);
  assert.match(core, /function pos_ensure_account_managers/);
  assert.match(core, /function pos_shop_support/);
  assert.match(core, /function pos_list_account_managers/);
  assert.match(core, /master\/account-managers/);
  assert.match(core, /businesses\/\(\[\^\/\]\+\)\/account-manager/);
  assert.match(core, /account_manager_id/);
  assert.match(read("pos-php-till.php"), /pos_shop_support\(\$bid\)/);
  assert.match(read("server/settings.js"), /export async function shopSupportContact/);
  assert.match(read("api/master/account-managers/index.php"), /master\/account-managers/);
  assert.match(read("api/master/alert-log/index.php"), /master\/alert-log/);
  assert.match(read("api/me/locale/index.php"), /me\/locale/);
  assert.match(read("api/master/languages/index.php"), /master\/languages/);
  assert.match(core, /function pos_normalize_locale/);
  assert.match(core, /function pos_ensure_i18n_columns/);
  assert.match(core, /me\/locale/);
  assert.match(core, /master\/languages/);
  assert.match(read("server/i18n.js"), /export function clipInvoiceText/);
  assert.match(read("server/i18n.js"), /export function attachInvoiceText/);
  assert.match(read("server/index.js"), /clipInvoiceText/);
  assert.match(till, /invoice_language/);
  assert.match(till, /invoice_footer/);
  assert.match(till, /invoice_terms/);
  assert.match(till, /payment_qr_url/);
  assert.match(till, /payment_upi/);
  assert.match(core, /function pos_clip_invoice_text/);
  assert.match(core, /function pos_attach_invoice_text/);
  assert.doesNotMatch(read("index.html"), /settings-pane-language/);
  assert.doesNotMatch(read("index.html"), /Language &amp; Region/);
  assert.match(read("index.html"), /id="set-invoice-footer"/);
  assert.match(read("index.html"), /id="set-invoice-terms"/);
  assert.match(read("index.html"), /id="set-pay-qr"/);
  assert.match(read("index.html"), /id="set-payment-upi"/);
  assert.match(read("index.html"), /i18n-catalog\.js/);
  assert.match(core, /master\/alert-log/);
  const ht = read("api/.htaccess");
  assert.match(ht, /DirectorySlash Off/);
  assert.doesNotMatch(ht, /!-d/);
  const apiJs = read("js/pos-api.js");
  assert.match(apiJs, /isPhpUnimplemented/);
  assert.match(apiJs, /orderedSpecs/);
  assert.match(apiJs, /localStorage.setItem\(STORAGE/);
  assert.match(apiJs, /window.posApiReady = Promise.resolve/);
  assert.doesNotMatch(apiJs, /window.posApiReady = ensureSpec\(\)/);
});

test("PHP customer insert bind types match placeholders", () => {
  const crud = read("pos-crud.php");
  const core = read("pos-php-core.php");
  const cust = crud.match(
    /INSERT INTO customers[\s\S]*?VALUES \(\?,\?,\?,\?,\?,\?,\?,\?,\?,0,\?\)",\s*"([sid]+)",\s*\[/,
  );
  assert.ok(cust, "customer INSERT found");
  assert.equal(cust[1].length, 10);
  assert.equal(cust[1], "ssssssssds");

  assert.match(crud, /color, size, wearer_type, base_unit/);
  const items = crud.match(/INSERT INTO items[\s\S]{0,500}"(ssssssssssddddssddss)"/);
  assert.ok(items, "item INSERT found");
  assert.equal(items[1].length, 20);
  assert.equal(items[1], "ssssssssssddddssddss");
  assert.match(core, /function pos_item_status/);
  assert.match(crud, /image_url/);
  assert.match(core, /function pos_item_image_url/);
  assert.match(core, /image_url.*MEDIUMTEXT/);
  assert.match(core, /pos-alerts\.php/);
  assert.match(core, /master\/alerts/);
  assert.match(core, /INSERT INTO notifications[\s\S]*image_url/);
  assert.match(read("pos-alerts.php"), /function pos_send_update_alerts/);
  assert.match(read("pos-alerts.php"), /function pos_notice_image/);
  assert.match(read("pos-alerts.php"), /cid:notice-image/);
  assert.match(read("pos-mail.php"), /Content-ID: <notice-image>/);
  assert.match(read("js/master.js"), /id="note-image"/);
  assert.match(read("js/app.js"), /notice-thumb/);

  assert.match(core, /function pos_ensure_business_columns/);
  assert.match(core, /function pos_is_footwear_shop/);
  assert.match(core, /function pos_is_apparel_shop/);
  assert.match(core, /function pos_is_variant_shop/);
  assert.match(core, /function pos_item_code_prefix/);
  assert.match(core, /AP-/);
  assert.match(core, /FW-/);
  assert.match(crud, /pos_is_variant_shop/);
  assert.match(crud, /pos_item_code_prefix/);
  assert.match(crud, /\$unitRaw = trim\(\(string\) \(\$body\["base_unit"\] \?\? \$body\["unit"\] \?\? ""\)\)/);
  assert.match(crud, /pos_default_item_unit\(\$biz\)/);
  assert.match(core, /function pos_shop_kind/);
  assert.match(core, /function pos_is_spice_shop/);
  assert.match(core, /GR-/);
  assert.match(core, /function pos_item_unit/);
  assert.match(read("pos-checkout.php"), /pos_line_amount_for_item/);
  assert.match(crud, /pos_line_amount_for_item/);
  assert.match(crud, /items\/import/);
  assert.match(read("pos-item-import.php"), /function pos_item_import_run/);
  assert.match(read("pos-item-import.php"), /pos_parse_item_xlsx/);
  assert.match(read("pos-item-import.php"), /\(string\) \$src, \$blocks/);
  assert.match(read("server/crud.js"), /\/api\/items\/import/);
  assert.match(read("server/item-import.js"), /ITEM_IMPORT_HEADERS/);
  assert.match(read("server/item-import.js"), /PHARMACY_ITEM_IMPORT_HEADERS/);
  assert.match(read("pos-item-import.php"), /Generic Name/);
  assert.match(read("pos-item-import.php"), /medicine_type/);
  assert.match(read("pos-php-core.php"), /pos_qr_public_dispatch/);
  assert.match(read("pos-php-till.php"), /pos_qr_staff_dispatch/);
  assert.match(read("pos-qr-ordering.php"), /ALTER TABLE qr_order_lines ADD COLUMN notes/);
  assert.match(read("server/qr-ordering.js"), /ALTER TABLE qr_order_lines ADD COLUMN notes/);
  assert.match(read("js/qr-order.js"), /Add Special Instruction/);
  assert.match(read("pos-qr-ordering.php"), /function pos_qr_ensure_invoice/);
  assert.match(read("pos-qr-ordering.php"), /sales_order_id/);
  assert.match(read("pos-checkout.php"), /qrOrderId/);
  assert.match(read("server/qr-ordering.js"), /export async function ensureQrInvoice/);
  assert.match(read("server/index.js"), /linkQrOrderSale/);
  assert.match(read("js/app.js"), /openInvoiceFromQr/);
  assert.match(read("js/app.js"), /data-qr-invoice/);
  assert.match(read("js/app.js"), /function printQrPoster/);
  assert.match(read("js/app.js"), /function printQrOrder/);
  assert.match(read("js/app.js"), /function qrOrderAsInvoice/);
  assert.match(read("js/app.js"), /function showInvoicePrintModal/);
  assert.match(read("js/app.js"), /printOrder\(bill, "pos"\)/);
  assert.match(read("js/app.js"), /Scan to order spices/);
  assert.match(read("js/app.js"), /Georgia,serif/);
  assert.match(read("js/app.js"), /#4a1416/);
  assert.match(read("js/app.js"), /data-qr-print/);
  assert.match(read("js/app.js"), /printQrOrder\(data\.order \|\| order, data\.invoice\)/);
  assert.match(read("server/index.js"), /registerQrPublic/);
  assert.match(read("server/index.js"), /registerQrStaff/);
  const index = read("index.html");
  assert.match(index, /js\/units\.js/);
  assert.match(index, /js\/footwear\.js/);
  assert.match(index, /id="item-wearer"/);
  assert.match(index, /id="item-unit"/);
  assert.match(index, /id="view-units"/);
  assert.match(index, /data-view="units"/);
  assert.match(read("pos-units.php"), /\$fam !== "weight" && \$fam !== "volume"/);
  assert.match(read("pos-php-core.php"), /pos_unit_is_count\(\$code\)/);
  assert.match(read("pos-units.php"), /CREATE TABLE IF NOT EXISTS inventory_units/);
  assert.match(read("pos-php-till.php"), /pos_dispatch_units/);
  assert.match(read("api/units/index.php"), /p.*=.*units/);
  const unitInsert = read("pos-units.php").match(
    /VALUES \(\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,'active'\)",\s*"([sid]+)",/,
  );
  assert.ok(unitInsert, "unit seed INSERT found");
  assert.equal(unitInsert[1], "sssssssdddi");
  const unitPost = read("pos-units.php").match(
    /VALUES \(\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?\)",\s*"([sid]+)",/,
  );
  assert.ok(unitPost, "unit POST INSERT found");
  assert.equal(unitPost[1], "sssssssdddis");
  assert.match(read("server/units.js"), /registerUnits/);
  assert.match(read("server/index.js"), /registerUnits\(app\)/);
  assert.match(read("js/app.js"), /applyUnitMaster/);
  assert.match(read("server/crud.js"), /POSUnits\.lineAmount/);
  assert.match(read("js/app.js"), /POSUnits\.lineAmount/);
  assert.match(read("pos-orders.php"), /pos_line_amount_for_item/);
  assert.match(read("pos-reports.php"), /payDaywise/);
  assert.match(read("pos-reports.php"), /Payment daywise/);
  assert.match(read("js/app.js"), /Payment daywise/);
  assert.match(read("server/reports.js"), /payDaywise/);
  const reportPhp = read("pos-reports.php");
  const reportJs = read("server/reports.js");
  assert.match(reportPhp, /GROUP BY i\.hsn, i\.code, l\.item_name, l\.gst_rate/);
  assert.match(reportJs, /GROUP BY i\.hsn, i\.code, l\.item_name, l\.gst_rate/);
  assert.doesNotMatch(reportPhp, /GROUP BY COALESCE\(i\.code/);
  assert.doesNotMatch(reportJs, /GROUP BY COALESCE\(i\.code/);
  assert.match(read("pos-php-core.php"), /\$db->error \?: "SQL error"/);
  assert.match(crud, /function pos_normalize_pack_items/);
  assert.match(crud, /function pos_insert_pack_lines/);
  assert.match(crud, /#\^packs\/\(\[\^\/\]\+\)\$#.*PUT/s);
  assert.match(crud, /DELETE FROM pack_items WHERE pack_id/);
  assert.match(read("server/crud.js"), /app\.put\("\/api\/packs\/:id"/);
  assert.match(read("js/app.js"), /data-edit-pack/);
  assert.match(read("js/app.js"), /Update pack/);
  assert.match(index, /id="pack-id"/);
});

test("PHP password hashes include sha256 and verify round-trip", { skip: hasPhpCli() ? false : "php CLI not installed" }, () => {
  const src = read("pos-php-scrypt.php");
  assert.match(src, /pos_password_needs_rehash/);
  assert.doesNotMatch(src, /return "pbkdf2\$sha256\$"/);
  const out = execFileSync(
    "php",
    [
      "-r",
      'require "pos-php-scrypt.php"; $h = pos_hash_password("Swami@12345"); if (!str_starts_with($h, \'pbkdf2$sha256$100000$\')) { fwrite(STDERR, $h); exit(2); } if (!pos_verify_password("Swami@12345", $h)) exit(3); if (pos_verify_password("wrong", $h)) exit(4); echo "HASH_OK needs=". (pos_password_needs_rehash($h) ? "yes" : "no");',
    ],
    { encoding: "utf8", cwd: root },
  );
  assert.match(out, /HASH_OK/);
  assert.match(out, /needs=no/);
});

test("Master Admin can set passwords and unlock locked accounts", () => {
  const masterJs = read("js/master.js");
  const masterApi = read("server/master.js");
  const core = read("pos-php-core.php");
  assert.match(masterJs, /data-reset-biz/);
  assert.match(masterJs, /data-reset-user/);
  assert.match(masterJs, /"Garments"/);
  assert.match(masterJs, /"Saree Shop"/);
  assert.match(masterJs, /"Ladies Fashion"/);
  assert.match(masterJs, /"Mens Fashion"/);
  assert.match(masterJs, /"Kids Fashion"/);
  assert.match(read("login.html"), />Boutique</);
  assert.match(masterJs, /data-unlock/);
  assert.match(masterJs, /accountStatusLabel/);
  assert.match(masterApi, /\/api\/master\/users\/:id\/unlock/);
  assert.match(masterApi, /\/api\/master\/businesses\/:id\/reset-password/);
  assert.match(masterApi, /\/api\/master\/businesses\/:id\/send-expiry-alert/);
  assert.match(masterApi, /\/api\/master\/alerts\/send-expiry/);
  assert.match(masterApi, /\/api\/master\/alerts\/send-expired/);
  assert.match(masterApi, /\/api\/master\/alerts\/send/);
  assert.match(masterApi, /\/api\/master\/alerts\/test/);
  assert.match(masterJs, /id="alert-send-test"/);
  assert.match(core, /master\/alerts\/test/);
  assert.match(masterJs, /send-alert-all-shops/);
  assert.match(core, /pos_send_manual_alerts|master\/alerts\/send/);
  assert.match(masterApi, /expiredOnly/);
  assert.match(masterApi, /\/api\/master\/businesses\/:id\/clean/);
  assert.match(masterJs, /data-send-expiry/);
  assert.match(masterJs, /alert-send-expiry/);
  assert.match(masterJs, /expiryAlertsPageHtml/);
  assert.match(masterJs, /expiry-send-expired/);
  assert.match(masterJs, /activationDate/);
  assert.match(masterApi, /activated_at/);
  assert.match(masterJs, /data-send-alert-row/);
  assert.match(masterJs, /data-clean-biz/);
  assert.match(masterJs, /function yearlyStartYmd/);
  assert.match(masterJs, /Fee ₹ \/ year/);
  assert.match(masterJs, /Every plan starts yearly/);
  assert.match(masterJs, /Fee \/ year/);
  assert.doesNotMatch(masterJs, /Fee ₹ \/ month/);
  assert.match(masterApi, /registerBusiness\(req\.body \|\| \{\}, \{ yearly: true \}\)/);
  assert.match(core, /pos_register_business\(\$body, true\)/);
  assert.match(core, /strtotime\("\+1 year"\)/);
  assert.match(read("server/onboard.js"), /INTERVAL 1 YEAR/);
  assert.match(read("master.html"), /master\.js\?v=20260922deploy208/);
  assert.match(read("js/app.js"), /Subscription fee \/ year/);
  assert.match(read("js/app.js"), /\["Valid till"/);
  assert.match(read("js/app.js"), /\["Days left"/);
  assert.match(read("js/app.js"), /function subscriptionValidity/);
  assert.match(read("pos-php-core.php"), /function pos_subscription_snapshot/);
  assert.match(read("pos-php-till.php"), /"subscription" => function_exists\("pos_subscription_snapshot"\)/);
  assert.match(read("server/tenant.js"), /DATEDIFF\(subscription_expires_at, CURDATE\(\)\)/);
  assert.match(read("server/tenant.js"), /subscription: \{/);
  assert.match(read("css/pos.css"), /\.dash-kpi\.is-warn/);
  assert.match(core, /users\/\(\[\^\/\]\+\)\/unlock/);
  assert.match(core, /businesses\/\(\[\^\/\]\+\)\/send-expiry-alert/);
  assert.match(core, /activated_at/);
  assert.match(core, /master\/alerts\/send-expired/);
  assert.match(core, /function pos_unlock_staff_user/);
  assert.match(core, /auth\/reset-password/);
  assert.match(read("js/app.js"), /data-edit-staff/);
  assert.match(read("js/app.js"), /\/api\/auth\/reset-password/);
  assert.match(read("index.html"), /id="password-form"/);
  assert.match(read("index.html"), /stock-desk/);
  assert.match(read("index.html"), /id="stock-hint"/);
  assert.match(read("index.html"), /id="stock-excel"/);
  assert.match(read("js/app.js"), /function resolvePickerItem/);
  assert.match(read("js/app.js"), /\/api\/stock\/excel/);
  assert.match(read("pos-php-till.php"), /stock\/excel/);
  assert.match(read("pos-stock-excel.php"), /function pos_stock_excel_response/);
  assert.match(read("pos-stock-excel.php"), /"name" => "SKUs"/);
  assert.match(read("pos-stock-excel.php"), /"Expiry"/);
  assert.match(read("pos-stock-excel.php"), /pos_stock_excel_row_from_batch/);
  assert.match(read("pos-advanced.php"), /on_hand/);
  assert.match(read("server/tenant.js"), /\/api\/stock\/excel/);
  assert.match(read("pos-crud.php"), /staff\/\(\[\^\/\]\+\)\$#.*PUT/s);
});

test("POS boot skips API probe and slims catalog photos", () => {
  const apiJs = read("js/pos-api.js");
  const appJs = read("js/app.js");
  const index = read("index.html");
  const login = read("login.html");
  const core = read("pos-php-core.php");
  const till = read("pos-php-till.php");
  const node = read("server/index.js");
  const loginJs = read("js/x-pos-20260830e.js");
  assert.match(apiJs, /pos_api_spec_v2/);
  assert.match(apiJs, /DEFAULT_SPEC/);
  assert.match(appJs, /showView\(landing\)/);
  assert.match(appJs, /function paintDeskState/);
  assert.match(index, /id="scale-dock"/);
  assert.match(index, /js\/scale\.js\?v=20260920scale4/);
  assert.match(appJs, /el\.textContent = "Dashboard"/);
  assert.match(index, /saas-dash-desk/);
  assert.match(index, /Business control center/);
  assert.match(index, /id="open-pos">New bill</);
  assert.match(read("css/pos.css"), /retail-analytics: colorful POS home 2026/);
  assert.match(appJs, /data-dash-view/);
  assert.match(appJs, /i.has_image/);
  assert.match(appJs, /requestIdleCallback/);
  assert.match(index, /i18n-catalog\.js[^>]+defer/);
  assert.match(index, /i18n\.js[^>]+defer/);
  assert.match(index, /qrcode\.iife\.js[^>]+defer/);
  assert.match(index, /preload="auto"/);
  assert.match(index, /pos-api\.js\?v=20260905deploy154/);
  assert.match(index, /app\.js\?v=20260922deploy207/);
  assert.match(index, /class="dialog-head"/);
  assert.match(index, /id="modal-close"/);
  assert.match(read("css/pos.css"), /#modal-close \{/);
  assert.match(index, /invoice-share\.js\?v=20260913share1/);
  assert.match(index, /invoice\.js\?v=20260922deploy210/);
  assert.doesNotMatch(index, /app\.js\?v=20260905deploy167/);
  assert.doesNotMatch(index, /app\.js\?v=20260905deploy166/);
  assert.match(index, /offers\.js\?v=20260905deploy170/);
  assert.match(index, /restaurant\.js\?v=20260918table1/);
  assert.match(login, /x-pos-20260830e\.js\?v=20260922deploy207/);
  assert.match(loginJs, /saveLoginSpec/);
  assert.match(core, /function pos_catalog_items/);
  assert.match(core, /function pos_slim_catalog_item/);
  assert.match(core, /pos_catalog_item_select_sql/);
  assert.match(till, /pos_catalog_items\(\$bid\)/);
  assert.match(till, /items\/\(\[a-zA-Z0-9-\]\+\)/);
  assert.match(node, /function listCatalogItems/);
  assert.match(node, /function slimCatalogItem/);
  assert.match(node, /app\.get\("\/api\/items\/:id"/);
  assert.match(node, /CATALOG_ITEM_SELECT/);
  assert.match(read("master.html"), /pos-api\.js\?v=20260905deploy154/);
});

test("Restaurant Counter can create named dining tables", () => {
  const app = read("js/app.js");
  const restaurant = read("js/restaurant.js");
  const css = read("css/pos.css");
  const index = read("index.html");
  const till = read("pos-php-till.php");
  const core = read("pos-php-core.php");
  const tenant = read("server/tenant.js");
  const schema = read("server/schema.js");
  assert.match(index, /id="table-board"/);
  assert.match(app, /data-add-table/);
  assert.match(app, /data-add-floor/);
  assert.match(app, /data-create-table/);
  assert.match(app, /data-create-floor/);
  assert.match(app, /\/api\/dining-tables/);
  assert.match(app, /function persistDiningTables/);
  assert.match(app, /function syncActiveFloor/);
  assert.match(app, /function qrMenuUrl/);
  assert.match(app, /&table=\$\{encodeURIComponent\(t\)\}/);
  assert.match(app, /function printQrTableStickers/);
  assert.match(app, /data-table-qr/);
  assert.match(index, /id="qr-table-codes"/);
  assert.match(index, /id="qr-print-all-tables"/);
  assert.match(restaurant, /function addTable/);
  assert.match(restaurant, /function addFloor/);
  assert.match(restaurant, /function tablesOf/);
  assert.match(restaurant, /function floorsOf/);
  assert.match(restaurant, /dining_tables_json/);
  assert.match(css, /\.table-create/);
  assert.match(css, /\.floor-chip/);
  assert.match(css, /body\.restaurant-mode \.table-board/);
  assert.match(tenant, /\/api\/dining-tables/);
  assert.match(tenant, /clipFloorId/);
  assert.match(schema, /dining_tables_json/);
  assert.match(core, /function pos_clip_dining_tables_json/);
  assert.match(core, /function pos_clip_floor_id/);
  assert.match(core, /dining_tables_json/);
  assert.match(till, /dining-tables/);
  assert.match(index, /pos\.css\?v=20260922deploy207/);
  assert.match(index, /restaurant\.js\?v=20260918table1/);
  assert.match(index, /app\.js\?v=20260922deploy207/);
  assert.match(index, /footwear\.js\?v=20260922deploy207/);
  assert.match(app, /function resolveKitchenKot/);
  assert.match(app, /function paintKotTimers/);
  assert.match(app, /data-kot-timer/);
  assert.match(css, /\.kot-timer/);
  assert.match(app, /Kitchen ticket saved/);
  assert.match(app, /function paintStaffRoleOptions/);
  assert.match(app, /function landingView/);
  assert.match(app, /\/api\/kots/);
  assert.match(index, /id="kot-list"/);
  assert.match(index, /id="kot-toast"/);
  assert.match(index, /id="kot-sound-toggle"/);
  assert.match(index, /id="kot-badge"/);
  assert.doesNotMatch(index, /india-pride/);
  assert.doesNotMatch(index, /make-in-india/);
  assert.doesNotMatch(index, /startup-india/);
  assert.match(restaurant, /function newKots/);
  assert.match(app, /function applyKotSnapshot/);
  assert.match(app, /function showKotToast/);
  assert.match(app, /p:not\(\.qr-toast-kicker\)/);
  assert.match(index, /option value="captain"/);
  assert.match(index, /option value="kitchen"/);
  assert.match(tenant, /requireBusinessAdmin/);
  assert.match(tenant, /\/api\/kots/);
  assert.match(till, /Only the business admin can manage tables and floors/);
  assert.match(core, /function pos_known_roles/);
  assert.match(schema, /kitchen_tickets/);
  assert.match(read("server/roles.js"), /"captain"/);
  assert.match(read("server/roles.js"), /"kitchen"/);
  assert.match(read("pos-kots.php"), /function pos_dispatch_kots/);
  assert.match(index, /data-view="prescriptions"/);
  assert.match(index, /id="view-prescriptions"/);
  assert.match(app, /rx\.html\?shop=/);
  assert.match(core, /rx\/shop.*rx\/prescriptions/s);
  assert.match(till, /prescriptions/);
  assert.match(app, /function loadPrescriptions/);
  assert.match(app, /function rxUploadUrl/);
});

test("PHP dining layout clip keeps floors and old table lists", { skip: hasPhpCli() ? false : "php CLI not installed" }, () => {
  const out = execFileSync(
    "php",
    [
      "-r",
      'require "pos-php-core.php"; $old = pos_clip_dining_tables_json(\'[{"id":"1","name":"Table 1"}]\'); $oldJ = json_decode($old, true); if (($oldJ["floors"][0]["id"] ?? "") !== "ground") exit(2); if (($oldJ["tables"][0]["floor"] ?? "") !== "ground") exit(3); $next = pos_clip_dining_tables_json(["floors"=>[["id"=>"ground","name"=>"Ground"],["id"=>"first","name"=>"First"]],"tables"=>[["id"=>"AC","name"=>"AC","floor"=>"first"]]]); $j = json_decode($next, true); if (count($j["floors"]) !== 2) exit(4); if (($j["tables"][0]["floor"] ?? "") !== "first") exit(5); echo "FLOOR_OK";',
    ],
    { encoding: "utf8", cwd: root },
  );
  assert.match(out, /FLOOR_OK/);
});

test("cancelled sales bills show Void in the shop UI and reports", () => {
  const app = read("js/app.js");
  const index = read("index.html");
  const crud = read("server/crud.js");
  const reports = read("server/reports.js");
  const phpOrders = read("pos-orders.php");
  const phpReports = read("pos-reports.php");
  assert.match(app, /if \(s === "cancelled"\) return "Void"/);
  assert.match(app, /Void invoice \$\{o\.order_number\}\? Stock will be restored\./);
  assert.match(app, /Change status from Void before editing items/);
  assert.match(app, /ORDER_STATUSES = \["confirmed", "delivered", "cancelled"\]/);
  assert.match(index, /<option value="cancelled">Void<\/option>/);
  assert.match(crud, /Void bills cannot be edited\. Change status first\./);
  assert.match(phpOrders, /Void bills cannot be edited\. Change status first\./);
  assert.match(reports, /=== "cancelled" \? "Void"/);
  assert.match(phpReports, /=== "cancelled" \? "Void"/);
  assert.match(read("js/invoice.js"), /function isVoidBill/);
  assert.match(read("js/invoice.js"), /return `<p class="\$\{cls\}">VOID<\/p>`/);
});

test("editing a saved bill keeps line and bill discounts on Save changes", () => {
  const app = read("js/app.js");
  const crud = read("server/crud.js");
  const phpOrders = read("pos-orders.php");
  assert.match(app, /function applyOrderDiscountsToCounter/);
  assert.match(app, /function cartLineFromOrderLine/);
  assert.match(app, /applyOrderDiscountsToCounter\(o\)/);
  assert.match(crud, /computeSaleLine\(item, customer, line\)/);
  assert.match(crud, /discount_type=\?, discount_value=\?/);
  assert.match(crud, /billDiscount/);
  assert.match(phpOrders, /pos_compute_sale_line/);
  assert.match(phpOrders, /pos_adv_discount_amount/);
  assert.match(phpOrders, /discount_type = \?, discount_value = \?/);
});

test("PHP website analytics public and master routes are wired", () => {
  const core = read("pos-php-core.php");
  const php = read("pos-analytics.php");
  const index = read("server/index.js");
  assert.match(core, /strpos\(\$path, "analytics\/"\) === 0/);
  assert.match(core, /strpos\(\$path, "master\/analytics"\) === 0/);
  assert.match(php, /website_analytics_settings/);
  assert.match(php, /pos_analytics_summarize/);
  assert.match(index, /registerAnalyticsPublic\(app\)/);
});
